import Head from 'next/head'
import React, { useState } from 'react'
import ufo from '../../../public/images/ufo.png';
import Image from "next/image";
import { useStore } from '@/lib/store';
import { BaseModal } from '@/components/BaseModal';
import { Box, Button, Flex } from '@chakra-ui/react';
import { v4 as uuidv4 } from 'uuid';

export default function Group() {
  const [groupName, setGroupName] = useState("")
  const { setGroupModalOpen, groupModalOpen, groups, setGroups } = useStore()

   // create group
	const handleSubmit = async () => {
    setGroups({
      id: uuidv4(),
      name: groupName
    })
    setGroupName("")
    setGroupModalOpen(false);
    // TODO:
	};

  return (
    <>
      <Head>
				<title>Create Api Key</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
      <div className='mt-[50px]'>
        { !groups.length ?
          <div className="flex flex-row justify-center items-center mx-20">
            <div className="mt-10 ">
              <div className='w-64 h-64 mx-auto my-5'>
                <Image src={ufo} alt='' className='w-full h-full object-cover'/>
              </div>
              <p className='font-jura text-xl text-center flex justify-center -mt-10'>No Group has been created for your account.</p>
              <div className="font-jura text-xl text-center flex justify-center mt-8">
                <button className='flex-shrink-0 mb-6 flex items-center p-1 px-4 rounded bg-stone-600 hover:bg-stone-700 active:bg-stone-500 focus:ring-stone-500 text-sm'
                  onClick={() => setGroupModalOpen(true)}>
                  Create Group
                </button>
              </div>
            </div>
          </div>:
          <div className='mx-20'>
          <h1 className='text-2xl font-bold'>Group</h1>
          <p className='text-xl my-2'>Select a group to store data</p>
          <div className='flex flex-wrap my-6'>
            <Button variant="grayPrimary" fontSize="sm" paddingX={6} color={"#fff"}
              className="!mt-[10px] h-[35px] leading-3 mr-4" onClick={() => setComModalOpen(true)}
            >
              Create Group
            </Button>
          </div>
          </div>
        }
      </div>
      <BaseModal isOpen={groupModalOpen}
        onClose={() => setGroupModalOpen(false)}>
          <Flex w="full" justifyContent="space-between" flexDirection="column">
            <div className='mt-[20px] lg:w-[400px] sm:w-[300px]'>
              <h3>Group Name</h3>
              <input
                type="text"
                placeholder="Please enter"
                className="my-6 text-[#000] w-full h-[35px] bg-[#A0A79F] font-swiss721md border-0 block"
                value={groupName}
                onChange={(e) => setGroupName(e.target.value)}
              />
              <p className='font-jura text-sm ml-2'>No Group has been created for your account.</p>
            </div>
            <Box mt={5} textAlign="right">
              <Button
                variant="grayPrimary"
                fontSize="sm"
                paddingX={6}
                color={groupName.length ? "#fff" : "#999" }
                isDisabled={!groupName.length}
                className="!mt-[10px] h-[35px] leading-3"
                onClick={handleSubmit}
              >
                Submit
              </Button>
            </Box>
          </Flex>
      </BaseModal>
    </>
  )
}
